apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-biddinggo-pvc
  namespace: biddinggo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: mariadb-biddinggo-pv
