apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-biddinggo-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /run/desktop/mnt/host/c/Users/Playdata/mariadb-biddinggo

