apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: biddinggo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis
        image: redis:7.4
        command:
        - sh
        - -c
        - redis-server --requirepass "$REDIS_PASSWORD"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: biddinggo-env-secret
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 6379
