apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: biddinggo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nueeaeel/biddinggo-cicd-private.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: biddinggo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
